// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
    numberOfOrders:           number;
    paidOrders:               number;
    numberOfClients:          number;
    numberOfProducts:         number;
    productsWhithNoInventory: number;
    lowInventory:             number;
    notPaidOrders:            number;
}
